# Generated by Django 4.1 on 2022-09-01 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("boteco", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="perfil",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("qtd_chifres", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("cm", "Corno Manso"),
                            ("cc", "Corno Cururu"),
                            ("ca", "Corno Abelha"),
                            ("cp", "Corno Prestativo"),
                            ("bg", "Buscando a galha"),
                            ("ci", "Corno Indeciso"),
                        ],
                        default="ci",
                        max_length=2,
                    ),
                ),
                (
                    "ultimo_chifre",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "procurando_mais",
                    models.BooleanField(
                        default=True, verbose_name="Procurando mais chifres"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Magote",
            fields=[
                (
                    "lider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="magote_lider",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membros",
                    models.ManyToManyField(
                        related_name="magote_membros", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
