# Generated by Django 4.1 on 2022-09-01 22:33

import boteco.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boteco", "0003_postagem_autor_postagem_curtidas_comentario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="foto_perfil",
            field=models.ImageField(
                blank=True,
                upload_to=boteco.models.user_directory_path,
                verbose_name="Foto de perfil",
            ),
        ),
    ]
