# Generated by Django 4.1 on 2022-09-01 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boteco", "0004_perfil_foto_perfil"),
    ]

    operations = [
        migrations.RenameField(
            model_name="perfil",
            old_name="user_id",
            new_name="user",
        ),
    ]
