# Generated by Django 4.1 on 2022-09-01 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boteco", "0005_rename_user_id_perfil_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="curtidas",
            field=models.ManyToManyField(
                blank=True,
                related_name="curtidas_comentarios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="postagem",
            name="comentarios",
            field=models.ManyToManyField(
                blank=True, related_name="postagem", to="boteco.comentario"
            ),
        ),
        migrations.AlterField(
            model_name="postagem",
            name="curtidas",
            field=models.ManyToManyField(
                blank=True,
                related_name="curtidas_postagem",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
