# Generated by Django 4.1 on 2022-09-01 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "boteco",
            "0006_alter_comentario_curtidas_alter_postagem_comentarios_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postagem",
            name="comentarios",
        ),
        migrations.AddField(
            model_name="comentario",
            name="postagem",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="boteco.postagem",
            ),
        ),
    ]
