# Generated by Django 4.1 on 2022-09-01 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boteco", "0007_remove_postagem_comentarios_comentario_postagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bebida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="perfil",
            name="bebida_preferida",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="boteco.bebida",
            ),
        ),
    ]
