# Generated by Django 4.1 on 2022-09-02 23:59

import boteco.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boteco", "0008_bebida_perfil_bebida_preferida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="foto_perfil",
            field=models.ImageField(
                blank=True,
                default="user_default/profile.jpg",
                upload_to=boteco.models.user_directory_path,
                verbose_name="Foto de perfil",
            ),
        ),
        migrations.AlterField(
            model_name="postagem",
            name="autor",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="postagens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
