# Generated by Django 4.1 on 2022-09-03 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boteco", "0009_alter_perfil_foto_perfil_alter_postagem_autor"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDeCorno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="perfil",
            name="status",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="boteco.tipodecorno",
            ),
        ),
    ]
