# Generated by Django 4.1 on 2022-08-19 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postagem",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
